[package]
name = "fast-srgb8"
version = "0.1.0"
edition = "2018"

[dependencies]


# [profile.release]
# debug-assertions = true
# overflow-checks = true
# [profile.test]
# debug-assertions = true
# overflow-checks = true
# [profile.bench]
# debug-assertions = false
# overflow-checks = false
